services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.retailio.ru
    container_name: mybusiness-front
    restart: unless-stopped
    expose:
      - "3005"
    environment:
      - VIRTUAL_HOST=retailio.ru
      - VIRTUAL_PORT=3005
      - LETSENCRYPT_HOST=retailio.ru
      - LETSENCRYPT_EMAIL=meoutic@gmail.com
      - NODE_ENV=production
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
